driver:
  name: dokken
  privileged: true
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true
  client_rb:
    silence_deprecation_warnings:
      # there is not much we can do to appease this short of breaking 99% of users/consumers
      - chef-25

verifier:
  name: inspec

platforms:
- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /sbin/init
    intermediate_instructions:
       - RUN /usr/bin/apt-get update

- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd
    intermediate_instructions:
       - RUN /usr/bin/apt-get update
  attributes:
    java:
      jdk_version: '8'

- name: centos-6
  driver:
    image: dokken/centos-6
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install sudo

- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install sudo

- name: fedora-latest
  driver:
    image: dokken/fedora-latest
    pid_one_command: /usr/lib/systemd/systemd
  attributes:
    java:
      jdk_version: '8'

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
       - RUN /usr/bin/apt-get update

- name: ubuntu-18.04
  driver:
    image: dokken/ubuntu-18.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
       - RUN /usr/bin/apt-get update
  attributes:
    java:
      jdk_version: '11'

- name: opensuse-leap
  driver:
    image: dokken/opensuse-leap
    pid_one_command: /bin/systemd
  attributes:
    java:
      # java cookbook doesnt properly default for opensuse
      # https://github.com/agileorbit-cookbooks/java/pull/446
      openjdk_packages: ['java-1_7_0-openjdk']

suites:
- name: default
  run_list:
  - recipe[test]
