name              'alltherubies'
maintainer        'Fletcher Nichol'
maintainer_email  'fnichol@nichol.ca'
license           'Apache 2.0'
description       'Installs all-the-rubies via ruby_build cookbook'
version           '0.1.0'

depends 'java'
depends 'user'
depends 'apt'
